export const data=[
    {
        id:1,
        name:'Bharatanatyam',
        img:'img1.jpg',
        img1:"https://www.holidify.com/images/cmsuploads/compressed/3531225584_d8f9ce5fd5_b_20170926204243.jpg",
        desc:'Tamil Nadu, South India',
        desc1:'Performed on the celestial tunes of the Carnatic music, Bharatnatyam comes from the state of Tamil Nadu in South. The origins of Bharatnatyam can be traced back to 1000 BC, and it originates from the ancient temples of Tamil Nadu performed by the women of the classical period. The dance form is known for its beautiful body movements and gestures which are called Mudras in the traditional language. It focuses on the hand gestures, leg movement and the facial expressions of the dancer. This dance form was very prevalent before the British era but was profoundly depressed during the colonial period. However, India kept the dance form alive in the houses, and today it is recognised as one of the most respectable art forms in India especially in the Southern region of the country where it is a moment of pride for the women of the house to learn the classical dance form of Bharatnatyam.',
    },
    {
        id:2,
        name:'Kathak',
        img:'img2.jpg',
        img1:"https://www.holidify.com/images/cmsuploads/compressed/33405125866_02c58f6e8a_b_20170926204513.jpg",
        desc:'Uttar Pradesh, North India',
        desc1:'Coming from the northern part of the country from the state of Uttar Pradesh Kathak comes from the word Katha which means story in Hindi. It isnt a very smart guess for one to make that Kathak is performed in the form of storytelling through the body movements used by the dancer. Kathak is often referred to as the dance of love and it can be performed by both by the male and female dancer together. This dance form focuses highly on the ankle movements complemented by the ankle that has to match the beats of the music. Ankle bells or gunghroos as they are called in the traditional language is an important part of the discipline of this dance form. Various distinctions can be witnessed in this dance forms as it is performed in various places in the country which includes Jaipur Benaras and Lucknow.',
    },
    {
        id:3,
        name:'Kathakali',
        img:'img3.jpg',
        img1:"https://www.holidify.com/images/cmsuploads/compressed/449px-Kathakalidancer_20170926204612.jpg",
        desc:'Kerala, South India',
        desc1:'Kathakali is another traditional dance form of India which relates to the storytelling. Kathakali translates to the storyteller in the countrys language. Coming from the Southern region of the country from Kerala. Kathakali is one of the most renowned and religious dances forms of India. It originates from the tales of Ramayana and Shiva stories. Kathakali includes the intriguing face movements and the heavy costumes which include the traditional face masks and body paints. The music which includes only the vocals is called Soppanam. The storytelling of the epic Hindu mythology tales depicting both evil and good is shown through the conversation between the dancers only through their body gestures and facial expressions.',
    },
    {
        id:4,
        name:'Manipuri',
        img:'img4.jpg',
        img1:"https://www.holidify.com/images/cmsuploads/compressed/486352442_28c34cbf1b_b_20170926204726.jpg", 
        desc:'Manipur, North East India',
        desc1:'As you stroll towards the North-east India which is brimming with the rich tradition and their unique culture, Manipuri comes as an important symbol to represent the state of Manipur from the region. This dance form is performed to narrate the romantic relationship between the Hindu gods Radha and Krishna, which is famously known as RaasLeela. This art form is performed in a team with the traditional Manipuri costumes and makeup to narrate the tale of the two gods. The dance is performed on the narrative chanting and the music created by the Indian classical instruments.',
    },
    {
        id:5,
        name:'Kuchipudi',
        img:"img5.jpg",
        img1:"https://www.holidify.com/images/cmsuploads/compressed/4048039772_4a3629ce62_o_20170927125955.jpg",
        desc:'Andhra Pradesh',
        desc1:'Belonging to the Andhra Pradesh, Kuchipudi is probably the toughest form of classical dance in India. Kuchipudi is not just considered as the dance but a whole religious procedure dedicated to God which includes certain rituals such as sprinkling the holy water burning the incense sticks and praying to God. Kuchipudi includes both singing and dancing by the performer which is why it requires both the skill and much more dedication than any other art forms in India. In the earlier period Kuchipudi was only performed by the male dancers in the temples specifically the Brahmins but with the passage of time it became famous amongst the women and nowadays it is mostly performed by the female dancers.',
    },
    {
        id:6,
        name:'Bhangra',
        img:"img7.jpg",
        img1:"https://www.holidify.com/images/cmsuploads/compressed/8451130049_7b1c16fd8c_b_20170927130153.jpg",
        desc:'Punjab, North India',
        desc1:'Belonging to Punjab, Bhangra is a heart-pumping dance adorned with the loud beats of dhol( traditional Indian instrument). It is very prevalent in traditional Punjabi festivals.',
    },
    {
        id:7,
        name:'Chhau',
        img:"img13.jpg",
        img1:"https://www.holidify.com/images/cmsuploads/compressed/Chhau_dance_20170927130356.jpg",
        desc:'Mayurbhanj, Odisha',
        desc1:'The beautiful women dressed in the elegant attire performing the dance form of Chhau is what you see during the festival time in Kolkata. The popular art coming from eastern India is considered as the dance in the form of martial arts.',
    },
    {
        id:8,
        name:'Garba',
        img:"img8.jpg",
        img1:"https://www.holidify.com/images/cmsuploads/compressed/Garba_20180310125915.jpg",
        desc:'Gujarat, West India',   
        desc1:'Garba comes from Gujarat which is a traditional dance form dedicated to Goddess Durga. It is performed in a couple on the typical Gujarati music, and the sticks are used to perform this art form.',   

    },
    {
        id:9,
        name:'Lavani',
        img:"img9.jfif",
        img1:"https://www.holidify.com/images/cmsuploads/compressed/Lavani_20180314221552.JPG",
        desc:'Maharashtra, West India',
        desc1:'Originated from the state of the Maratha empire, Lavani is a dance form of Maharashtra. The female-oriented dance is a blend of traditional music and tales of deities. The origin of Lavani comes from the word Lavanya which means beauty. Apart from helping in the upliftment of the Marathi folk theatre the dance form was also a morale booster during the war in the 18th century. Lavani has two forms One thats philosophical Nirguni Lavani and the other thats sensual Shringar Lavani. With the powerful and quick foot-tapping tempo the dance form is performed along with the beats of the Dholak. The stories or subjects this dance is based on revolves around topics of religion politics society and mostly romance. Dancers are dressed in nine-yard of saree with golden jewellery. The dance was initially staged at local temples in the form of worship but now it s a sensual dance performed to the pulsating beats rendering a socio political satire.',
    },
    {
        id:10,
        name:'Sattriya Dance',
        img:"img11.jpg",
        imf1:"https://www.holidify.com/images/cmsuploads/compressed/Sattriya_Dancer_Krishnakshi_Kashyap_20191009120225.jpg",
        desc:'Assam, North East India',
        desc1:'Mahapurusha Sankaradeva a Vaishnava saint and reformer of Assam introduced Sattriya dance in the 15th century AD. This dance form was preserved in the Sattras or the Vaishnava Maths therefore it remained a living tradition. This dance was an artistic way of presenting mythological teachings. Traditionally this dance was performed by the male monks or bhokots. However today the practice has changed in many ways. The theme is not just related to mythology and the performances are not limited to the Sattras. Even women can perform Sattriya dance and on the stage.',
    }
    

]
